/*
 * Doi Server API
 * Doi Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fr.cnes.doi.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import fr.cnes.doi.client.ApiException;
import fr.cnes.doi.client.api.CitationApi;

/**
 * API tests for CitationApi
 */
public class CitationApiTest {

    private final CitationApi api = new CitationApi();

    
    /**
     * 
     *
     * Returns the formatted citation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitationTest() throws ApiException {
        String doi = "10.23641/asha.5233939";
        String style = "annales";
        String lang = "ar";
        String response = api.getCitation(doi, style, lang);
        assert(response.equals("Elina Niemitalo-Haapola, Sini Haapala, Teija Kujala, Antti Raappana, Tiia Kujala و Eira Jansson-Verkasalo, \"Developmental and noise-induced changes (Niemitalo-Haapola et al., 2017)\".\n"));
    }
    
    /**
     * 
     *
     * Renvoie la liste des langages disponibles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitationsLanguageTest() throws ApiException {
        List<String> response = api.getCitationsLanguage();
        assert(!response.equals(TestUtil.languages)); 
    }
    
    /**
     * 
     *
     * Renvoie la liste des styles disponibles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitationsStyleTest() throws ApiException {
        List<String> response = api.getCitationsStyle();
        assert(!response.isEmpty());
    }
    
}
