/*
 * Doi Server API
 * A Digital Object Identifier (DOI) is an alphanumeric string assigned to uniquely identify an object. It is tied to a metadata description of the object as well as to a digital location, such as a URL, where all the details about the object are accessible. This documentation provides an API to query the DOI-server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jean-christophe.malapert@cnes.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DoiCitationFormatterApi
 */
@Ignore
public class DoiCitationFormatterApiTest {

    private final DoiCitationFormatterApi api = new DoiCitationFormatterApi();

    
    /**
     * 
     *
     * Returns the formatted citation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitationTest() throws ApiException {
        String doi = null;
        String style = null;
        String lang = null;
        String response = api.getCitation(doi, style, lang);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Renvoie la liste des langages disponibles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitationsLanguageTest() throws ApiException {
        List<String> response = api.getCitationsLanguage();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Renvoie la liste des styles disponibles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitationsStyleTest() throws ApiException {
        List<String> response = api.getCitationsStyle();

        // TODO: test validations
    }
    
}
